import { useEffect, useMemo, useState } from "react";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Image as ImageIcon, Users, X } from "lucide-react";
import IconInput from "@/components/common/IconInput";
import SimpleSelect from "@/components/common/SimpleSelect";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldLegend, FieldSet } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useFacilities } from "@/hooks/useFacilities";
import { useRoomMutations } from "@/hooks/useRooms";
import { useToast } from "@/hooks/useToast";
import { applyApiErrors, errorMessage } from "@/lib/formErrors";

const statusOptions = [
  { value: "available", label: "Available" },
  { value: "occupied", label: "Occupied" },
  { value: "maintenance", label: "Under maintenance" },
];

// Mirrors the API's own limits (see Quorum-BE/src/config/constants.js and middlewares/upload.js),
// so an obviously invalid file is caught before it is even uploaded.
const ACCEPTED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"];
const MAX_IMAGE_BYTES = 5 * 1024 * 1024;

const schema = z.object({
  // Name uniqueness is enforced by the API (409), which the form maps back onto this field.
  name: z.string().trim().min(2, "Enter a room name."),
  floor: z.string().trim().min(2, "Enter the floor or location."),
  capacity: z
    .string()
    .regex(/^\d+$/, "Enter a whole number.")
    .refine((v) => Number(v) >= 1 && Number(v) <= 100, "Capacity must be between 1 and 100."),
  status: z.enum(["available", "occupied", "maintenance"]),
  description: z.string().trim().max(400, "Keep the description under 400 characters."),
  imageFile: z
    .instanceof(File)
    .nullable()
    .refine((f) => !f || ACCEPTED_IMAGE_TYPES.includes(f.type), "Choose a JPEG, PNG or WEBP image.")
    .refine((f) => !f || f.size <= MAX_IMAGE_BYTES, "Image must be at most 5 MB."),
  facilities: z.array(z.string()),
});

// "image" is deliberately absent: it is always either omitted or a URL this app just generated by
// uploading a file, never something the room form itself collects, so there is no field to show it on.
const FIELDS = ["name", "floor", "capacity", "status", "description", "facilities"];

function RoomFormBody({ room, onSubmit, onCancel }) {
  const { notify } = useToast();
  const { facilities } = useFacilities();
  const { uploadRoomImage } = useRoomMutations();
  const [fileInputKey, setFileInputKey] = useState(0); // bumped to reset the (uncontrolled) file input
  const { control, handleSubmit, setError, formState } = useForm({
    resolver: zodResolver(schema),
    mode: "onTouched",
    defaultValues: {
      name: room?.name ?? "",
      floor: room?.floor ?? "",
      capacity: String(room?.capacity ?? 6),
      status: room?.status ?? "available",
      description: room?.description ?? "",
      imageFile: null,
      facilities: room?.facilities ?? [],
    },
  });

  const submit = async (v) => {
    try {
      let image;
      if (v.imageFile) {
        try {
          image = await uploadRoomImage(v.imageFile);
        } catch (err) {
          // A rejected upload (e.g. the file's actual bytes aren't really an image) is reported on
          // this field, same as any other server validation error, and the room is never touched.
          if (!applyApiErrors(err, setError, ["imageFile"])) setError("imageFile", { type: "server", message: errorMessage(err) });
          return;
        }
      }

      await onSubmit({
        name: v.name.trim(),
        floor: v.floor.trim(),
        capacity: Number(v.capacity),
        status: v.status,
        description: v.description.trim(),
        facilities: v.facilities,
        // No new file: keep the existing photo when editing, or the server's default when adding.
        ...(image && { image }),
      });
    } catch (err) {
      // Field problems (duplicate name, bad values) land on their inputs; anything else becomes a toast.
      if (!applyApiErrors(err, setError, FIELDS)) notify("Could not save the room", { description: errorMessage(err), variant: "danger" });
    }
  };

  return (
    <form onSubmit={handleSubmit(submit)} noValidate className="grid gap-6">
      <FieldGroup className="gap-6">
        <Controller
          name="name"
          control={control}
          render={({ field, fieldState }) => (
            <Field data-invalid={fieldState.invalid}>
              <FieldLabel htmlFor="room-name">Room name</FieldLabel>
              <Input {...field} id="room-name" placeholder="e.g. Meridian" aria-invalid={fieldState.invalid} />
              {fieldState.invalid && <FieldError errors={[fieldState.error]} />}
            </Field>
          )}
        />
        <Controller
          name="floor"
          control={control}
          render={({ field, fieldState }) => (
            <Field data-invalid={fieldState.invalid}>
              <FieldLabel htmlFor="room-floor">Floor and wing</FieldLabel>
              <Input {...field} id="room-floor" placeholder="e.g. Floor 8, West Wing" aria-invalid={fieldState.invalid} />
              {fieldState.invalid && <FieldError errors={[fieldState.error]} />}
            </Field>
          )}
        />
        <Controller
          name="capacity"
          control={control}
          render={({ field, fieldState }) => (
            <Field data-invalid={fieldState.invalid}>
              <FieldLabel htmlFor="room-capacity">Capacity</FieldLabel>
              <IconInput {...field} id="room-capacity" type="number" min={1} icon={Users} aria-invalid={fieldState.invalid} />
              {fieldState.invalid && <FieldError errors={[fieldState.error]} />}
            </Field>
          )}
        />
        <Controller
          name="status"
          control={control}
          render={({ field }) => (
            <Field>
              <FieldLabel htmlFor="room-status">Status</FieldLabel>
              <SimpleSelect id="room-status" value={field.value} onValueChange={field.onChange} options={statusOptions} />
            </Field>
          )}
        />
        <Controller
          name="description"
          control={control}
          render={({ field, fieldState }) => (
            <Field data-invalid={fieldState.invalid}>
              <FieldLabel htmlFor="room-description">Description</FieldLabel>
              <Textarea {...field} id="room-description" rows={3} aria-invalid={fieldState.invalid} />
              {fieldState.invalid && <FieldError errors={[fieldState.error]} />}
            </Field>
          )}
        />
        <Controller
          name="imageFile"
          control={control}
          render={({ field, fieldState }) => (
            <RoomPhotoField
              file={field.value}
              onChange={field.onChange}
              existingImage={room?.image}
              invalid={fieldState.invalid}
              error={fieldState.error}
              inputKey={fileInputKey}
              onClear={() => setFileInputKey((k) => k + 1)}
            />
          )}
        />
        <Controller
          name="facilities"
          control={control}
          render={({ field }) => (
            <FieldSet>
              <FieldLegend variant="label">Facilities</FieldLegend>
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                {facilities.map((f) => {
                  const id = `facility-${f.replace(/\s+/g, "-").toLowerCase()}`;
                  return (
                    <div key={f} className="flex items-center gap-3">
                      <Checkbox
                        id={id}
                        checked={field.value.includes(f)}
                        onCheckedChange={(checked) =>
                          field.onChange(checked ? [...field.value, f] : field.value.filter((x) => x !== f))
                        }
                      />
                      <Label htmlFor={id} className="font-medium text-foreground/80">
                        {f}
                      </Label>
                    </div>
                  );
                })}
              </div>
            </FieldSet>
          )}
        />
      </FieldGroup>

      <DialogFooter className="-mx-6 -mb-6 mt-2">
        <Button type="button" variant="outline" onClick={onCancel}>
          Cancel
        </Button>
        <Button type="submit" disabled={formState.isSubmitting}>
          {formState.isSubmitting ? "Saving…" : room ? "Save changes" : "Add room"}
        </Button>
      </DialogFooter>
    </form>
  );
}

// A thumbnail preview plus a native file picker. The input stays uncontrolled (browsers refuse to
// set a file input's value programmatically); `inputKey` is bumped by the parent to reset it.
function RoomPhotoField({ file, onChange, existingImage, invalid, error, inputKey, onClear }) {
  // Recomputed only when the selected file changes; the effect below just releases the previous
  // one (a browser resource, not React state), so there is nothing to synchronise via setState.
  const previewUrl = useMemo(() => (file ? URL.createObjectURL(file) : null), [file]);
  useEffect(() => () => previewUrl && URL.revokeObjectURL(previewUrl), [previewUrl]);

  const displaySrc = previewUrl ?? existingImage;

  return (
    <Field data-invalid={invalid}>
      <FieldLabel htmlFor="room-image">Room photo</FieldLabel>
      <div className="flex items-start gap-4">
        <div className="relative aspect-[16/10] w-32 shrink-0 overflow-hidden rounded-lg bg-tint-soft">
          {displaySrc ? (
            <img src={displaySrc} alt="" className="h-full w-full object-cover" />
          ) : (
            <div className="flex h-full items-center justify-center text-primary-soft">
              <ImageIcon size={22} strokeWidth={1.75} />
            </div>
          )}
          {file && (
            <button
              type="button"
              onClick={() => {
                onChange(null);
                onClear();
              }}
              aria-label="Remove selected photo"
              // A scrim over the photo thumbnail, not the page: always a dark circle with a light
              // icon, in both themes, like a photo viewer's own controls.
              className="absolute top-1.5 right-1.5 grid size-6 place-items-center rounded-full bg-ink/70 text-canvas outline-none hover:bg-ink focus-visible:ring-3 focus-visible:ring-ring/50"
            >
              <X size={14} />
            </button>
          )}
        </div>
        <div className="min-w-0 flex-1 space-y-2">
          <Input
            key={inputKey}
            id="room-image"
            type="file"
            accept={ACCEPTED_IMAGE_TYPES.join(",")}
            aria-invalid={invalid}
            onChange={(e) => onChange(e.target.files?.[0] ?? null)}
          />
          <FieldDescription>
            JPEG, PNG or WEBP, up to 5 MB.{" "}
            {existingImage ? "Leave empty to keep the current photo." : "Leave empty to use a default photo."}
          </FieldDescription>
          {invalid && <FieldError errors={[error]} />}
        </div>
      </div>
    </Field>
  );
}

// room = null adds a new room; a room object edits it.
export default function RoomFormDialog({ open, onOpenChange, room, onSubmit }) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>{room ? `Edit ${room.name}` : "Add a room"}</DialogTitle>
          <DialogDescription>
            {room ? "Changes apply immediately across the employee and admin views." : "New rooms appear in Find a room straight away."}
          </DialogDescription>
        </DialogHeader>
        <RoomFormBody room={room} onSubmit={onSubmit} onCancel={() => onOpenChange(false)} />
      </DialogContent>
    </Dialog>
  );
}
